
package pruebas;

import javax.swing.JOptionPane;


public class Menu extends javax.swing.JFrame {

   
    public Menu() {
        initComponents();
        //se cambia el titulo del frame
        this.setTitle("Operaciones");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnSalir = new javax.swing.JButton();
        btnSuma = new javax.swing.JButton();
        lblDescripcion = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnResta = new javax.swing.JButton();
        btnMultiplicacion = new javax.swing.JButton();
        btnDivision = new javax.swing.JButton();
        btnRaiz = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        btnSalir.setBackground(new java.awt.Color(0, 0, 0));
        btnSalir.setForeground(new java.awt.Color(255, 204, 0));
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir);
        btnSalir.setBounds(280, 450, 90, 32);

        btnSuma.setBackground(new java.awt.Color(0, 0, 0));
        btnSuma.setForeground(new java.awt.Color(255, 204, 0));
        btnSuma.setText("Suma");
        btnSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumaActionPerformed(evt);
            }
        });
        jPanel1.add(btnSuma);
        btnSuma.setBounds(37, 180, 120, 32);

        lblDescripcion.setFont(new java.awt.Font("Footlight MT Light", 1, 14)); // NOI18N
        lblDescripcion.setForeground(new java.awt.Color(0, 0, 0));
        lblDescripcion.setText("Eliga una operacion a efectuar");
        jPanel1.add(lblDescripcion);
        lblDescripcion.setBounds(90, 110, 210, 40);

        jLabel1.setFont(new java.awt.Font("Footlight MT Light", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Operaciones");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(120, 20, 170, 90);

        btnResta.setBackground(new java.awt.Color(0, 0, 0));
        btnResta.setForeground(new java.awt.Color(255, 204, 0));
        btnResta.setText("Resta");
        btnResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestaActionPerformed(evt);
            }
        });
        jPanel1.add(btnResta);
        btnResta.setBounds(230, 180, 120, 32);

        btnMultiplicacion.setBackground(new java.awt.Color(0, 0, 0));
        btnMultiplicacion.setForeground(new java.awt.Color(255, 204, 0));
        btnMultiplicacion.setText("Multiplicacion");
        btnMultiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplicacionActionPerformed(evt);
            }
        });
        jPanel1.add(btnMultiplicacion);
        btnMultiplicacion.setBounds(230, 260, 120, 32);

        btnDivision.setBackground(new java.awt.Color(0, 0, 0));
        btnDivision.setForeground(new java.awt.Color(255, 204, 0));
        btnDivision.setText("Division");
        btnDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivisionActionPerformed(evt);
            }
        });
        jPanel1.add(btnDivision);
        btnDivision.setBounds(40, 260, 120, 32);

        btnRaiz.setBackground(new java.awt.Color(0, 0, 0));
        btnRaiz.setForeground(new java.awt.Color(255, 204, 0));
        btnRaiz.setText("Raiz cuadrada");
        btnRaiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRaizActionPerformed(evt);
            }
        });
        jPanel1.add(btnRaiz);
        btnRaiz.setBounds(130, 330, 120, 32);

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pruebas/back.jpg"))); // NOI18N
        jPanel1.add(lblFondo);
        lblFondo.setBounds(0, -10, 390, 530);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Este boton finaliza con el programa
    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
         System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumaActionPerformed
//Se hace uso de try para capturar errores
        try{
            /*se hace una instancia de cada subclase por boton y se utilizan los metodos cargar1, cargar2 y mostrarresultado
            este ultimo metodo lleva dentro operar*/
        Suma adicion = new Suma();
    adicion.cargar1(Double.parseDouble(JOptionPane.showInputDialog(null, "Ingrese el valor del primer numero a sumar")));
    adicion.cargar2(Double.parseDouble(JOptionPane.showInputDialog(null, "Ingrese el valor del primer numero a sumar")));
    adicion.mostrarresultado();
    //se capturan errores como letras o palabras
    }catch(NumberFormatException ex){
       JOptionPane.showMessageDialog(null, "Dato incorrecto");
    }
    }//GEN-LAST:event_btnSumaActionPerformed

    private void btnMultiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplicacionActionPerformed
 try{
                 /*se hace una instancia de cada subclase por boton y se utilizan los metodos cargar1, cargar2 y mostrarresultado
            este ultimo metodo lleva dentro operar*/
        Multiplicacion m = new Multiplicacion();
   m.cargar1(Double.parseDouble(JOptionPane.showInputDialog(null, "Ingrese el valor del primer numero a multiplicar")));
   m.cargar2(Double.parseDouble(JOptionPane.showInputDialog(null, "Ingrese el valor del Segundo numero a multiplicar")));
   m.mostrarresultado();
     }catch(NumberFormatException ex){
       JOptionPane.showMessageDialog(null, "Dato incorrecto");
    }
    }//GEN-LAST:event_btnMultiplicacionActionPerformed

    private void btnRaizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRaizActionPerformed
      try{
                      /*se hace una instancia de cada subclase por boton y se utilizan los metodos cargar1, cargar2 y mostrarresultado
            este ultimo metodo lleva dentro operar*/
        RaizCuadrada rai = new RaizCuadrada();
       rai.cargar1(Double.parseDouble(JOptionPane.showInputDialog(null, "Ingrese el valor a obtener su raiz con radical " + rai.radical )));
       rai.mostrarresultado();
         }catch(NumberFormatException ex){
       JOptionPane.showMessageDialog(null, "Dato incorrecto");
    }
    }//GEN-LAST:event_btnRaizActionPerformed

    private void btnRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestaActionPerformed
       try{
                       /*se hace una instancia de cada subclase por boton y se utilizan los metodos cargar1, cargar2 y mostrarresultado
            este ultimo metodo lleva dentro operar*/
     Resta res = new Resta();
     res.cargar1(Double.parseDouble(JOptionPane.showInputDialog(null, "Ingrese el valor del primer numero a restar")));
   res.cargar2(Double.parseDouble(JOptionPane.showInputDialog(null, "Ingrese el valor del Segundo numero a restar")));
   res.mostrarresultado();
         }catch(NumberFormatException ex){
       JOptionPane.showMessageDialog(null, "Dato incorrecto");
    }
    }//GEN-LAST:event_btnRestaActionPerformed

    private void btnDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivisionActionPerformed
       try{
                       /*se hace una instancia de cada subclase por boton y se utilizan los metodos cargar1, cargar2 y mostrarresultado
            este ultimo metodo lleva dentro operar*/
           Division div = new Division();
          div.cargar1(Double.parseDouble(JOptionPane.showInputDialog(null, "Ingrese el valor del dividendo")));
   div.cargar2(Double.parseDouble(JOptionPane.showInputDialog(null, "Ingrese el valor del divisor")));
   div.mostrarresultado();
        }catch(NumberFormatException ex){
       JOptionPane.showMessageDialog(null, "Dato incorrecto");
    }
    }//GEN-LAST:event_btnDivisionActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDivision;
    private javax.swing.JButton btnMultiplicacion;
    private javax.swing.JButton btnRaiz;
    private javax.swing.JButton btnResta;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSuma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblFondo;
    // End of variables declaration//GEN-END:variables
}
